include ../../Makefile.test.globals

TESTS=	\
				t_BulgeChasing_1 \
				t_EliminazioneGaussiana_1 \
				t_EliminazioneGaussiana_2 \
				t_EliminazioneGaussiana_3 \
				t_EliminazioneGaussiana_4 \
				t_EliminazioneGaussiana_5 \
				t_EliminazioneGaussiana_6 \
				t_EliminazioneGaussiana_7 \
				t_EliminazioneGaussiana_8 \
				t_FattorizzazioneLU_1 \
				t_FattorizzazioneLU_2 \
				t_FattorizzazioneLU_3 \
				t_FattorizzazioneLU_4 \
				t_FattorizzazioneLU_5 \
				t_FattorizzazioneLU_6 \
				t_FattorizzazioneLU_7 \
				t_FattorizzazioneLU_8 \
				t_FattorizzazioneLUP_1 \
				t_FattorizzazioneLUP_2 \
				t_FattorizzazioneLUP_3 \
				t_FattorizzazioneLUP_4 \
				t_FattorizzazioneLUP_5 \
				t_FattorizzazioneLUP_6 \
				t_FattorizzazioneLUP_7 \
				t_FattorizzazioneLUP_8 \
				t_FattorizzazioneQR_1 \
				t_FattorizzazioneQR_2 \
				t_FattorizzazioneQR_3 \
				t_FattorizzazioneQR_4 \
				t_FattorizzazioneQR_5 \
				t_FattorizzazioneQR_6 \
				t_FattorizzazioneQR_7 \
				t_FattorizzazioneQR_8 \
				t_HessenbergViaGivens_1 \
				t_HessenbergViaHouseholder_1 \
				t_MetodoDiGaussSeidel_1 \
				t_MetodoDiJacobi_1 \
				t_MetodoDiRichardson_1 \
				t_OrtonormalizzaColonne_1 \
				t_OrtonormalizzaColonne_2 \
				t_OrtonormalizzaColonne_3 \
				t_OrtonormalizzaColonne_4 \
				t_OrtonormalizzaColonne_5 \
				t_OrtonormalizzaColonne_6 \
				t_OrtonormalizzaColonne_7 \
				t_OrtonormalizzaColonne_8 \
				t_Schur_1 \
				t_SostituzioneAllIndietro_1 \
				t_SostituzioneAllIndietro_2 \
				t_SostituzioneAllIndietro_3

t_BulgeChasing_1.out: t_BulgeChasing_1.m \
								QuasiHessenberg_1 \
								../BulgeChasing.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_1.out: t_EliminazioneGaussiana_1.m \
															Quadrata_Triangolare \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_2.out: t_EliminazioneGaussiana_2.m \
															Rettangolare_Triangolare_1 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_3.out: t_EliminazioneGaussiana_3.m \
															Rettangolare_Triangolare_2 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_4.out: t_EliminazioneGaussiana_4.m \
															Rettangolare_1 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_5.out: t_EliminazioneGaussiana_5.m \
															Rettangolare_2 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_6.out: t_EliminazioneGaussiana_6.m \
															Rettangolare_3 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_7.out: t_EliminazioneGaussiana_7.m \
															Rettangolare_4 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_EliminazioneGaussiana_8.out: t_EliminazioneGaussiana_8.m \
															Rettangolare_5 \
															../EliminazioneGaussiana.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_1.out: t_FattorizzazioneLU_1.m \
															Quadrata_Triangolare \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_2.out: t_FattorizzazioneLU_2.m \
															Rettangolare_Triangolare_1 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_3.out: t_FattorizzazioneLU_3.m \
															Rettangolare_Triangolare_2 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_4.out: t_FattorizzazioneLU_4.m \
															Rettangolare_1 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_5.out: t_FattorizzazioneLU_5.m \
															Rettangolare_2 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_6.out: t_FattorizzazioneLU_6.m \
															Rettangolare_3 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_7.out: t_FattorizzazioneLU_7.m \
															Rettangolare_4 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLU_8.out: t_FattorizzazioneLU_8.m \
															Rettangolare_5 \
															../FattorizzazioneLU.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_1.out: t_FattorizzazioneLUP_1.m \
															Quadrata_Triangolare \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_2.out: t_FattorizzazioneLUP_2.m \
															Rettangolare_Triangolare_1 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_3.out: t_FattorizzazioneLUP_3.m \
															Rettangolare_Triangolare_2 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_4.out: t_FattorizzazioneLUP_4.m \
															Rettangolare_1 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_5.out: t_FattorizzazioneLUP_5.m \
															Rettangolare_2 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_6.out: t_FattorizzazioneLUP_6.m \
															Rettangolare_3 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_7.out: t_FattorizzazioneLUP_7.m \
															Rettangolare_4 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneLUP_8.out: t_FattorizzazioneLUP_8.m \
															Rettangolare_5 \
															../FattorizzazioneLUP.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_1.out: t_FattorizzazioneQR_1.m \
															Quadrata_Triangolare \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_2.out: t_FattorizzazioneQR_2.m \
															Rettangolare_Triangolare_1 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_3.out: t_FattorizzazioneQR_3.m \
															Rettangolare_Triangolare_2 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_4.out: t_FattorizzazioneQR_4.m \
															Rettangolare_1 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_5.out: t_FattorizzazioneQR_5.m \
															Rettangolare_2 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_6.out: t_FattorizzazioneQR_6.m \
															Rettangolare_3 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_7.out: t_FattorizzazioneQR_7.m \
															Rettangolare_4 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_FattorizzazioneQR_8.out: t_FattorizzazioneQR_8.m \
															Rettangolare_5 \
															../FattorizzazioneQR.m
	${OCTAVE_CMD} > $@

t_HessenbergViaGivens_1.out: t_HessenbergViaGivens_1.m \
								Quadrata_1 \
								../HessenbergViaGivens.m
	${OCTAVE_CMD} > $@

t_HessenbergViaHouseholder_1.out: t_HessenbergViaHouseholder_1.m \
								Quadrata_1 \
								../HessenbergViaHouseholder.m
	${OCTAVE_CMD} > $@

t_MetodoDiGaussSeidel_1.out: t_MetodoDiGaussSeidel_1.m \
												Quadrata_FortementeDominanteDiagonale_1 \
											../MetodoDiGaussSeidel.m
	${OCTAVE_CMD} > $@

t_MetodoDiJacobi_1.out: t_MetodoDiJacobi_1.m \
												Quadrata_FortementeDominanteDiagonale_1 \
											../MetodoDiJacobi.m
	${OCTAVE_CMD} > $@

t_MetodoDiRichardson_1.out: t_MetodoDiRichardson_1.m \
												Quadrata_FortementeDominanteDiagonale_1 \
											../MetodoDiRichardson.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_1.out: t_OrtonormalizzaColonne_1.m \
															Quadrata_Triangolare \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_2.out: t_OrtonormalizzaColonne_2.m \
															Rettangolare_Triangolare_1 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_3.out: t_OrtonormalizzaColonne_3.m \
															Rettangolare_Triangolare_2 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_4.out: t_OrtonormalizzaColonne_4.m \
															Rettangolare_1 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_5.out: t_OrtonormalizzaColonne_5.m \
															Rettangolare_2 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_6.out: t_OrtonormalizzaColonne_6.m \
															Rettangolare_3 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_7.out: t_OrtonormalizzaColonne_7.m \
															Rettangolare_4 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_OrtonormalizzaColonne_8.out: t_OrtonormalizzaColonne_8.m \
															Rettangolare_5 \
															../OrtonormalizzaColonne.m \
															../../${OCTAVE_LIB}/VerificaSeZero.m
	${OCTAVE_CMD} > $@

t_Schur_1.out: t_Schur_1.m \
								Quadrata_1 \
								../Schur.m
	${OCTAVE_CMD} > $@

t_SostituzioneAllIndietro_1.out: t_SostituzioneAllIndietro_1.m \
															Quadrata_Triangolare \
															../SostituzioneAllIndietro.m
	${OCTAVE_CMD} > $@

t_SostituzioneAllIndietro_2.out: t_SostituzioneAllIndietro_2.m \
															Rettangolare_Triangolare_1 \
															../SostituzioneAllIndietro.m
	${OCTAVE_CMD} > $@

t_SostituzioneAllIndietro_3.out: t_SostituzioneAllIndietro_3.m \
															Rettangolare_Triangolare_2 \
															../SostituzioneAllIndietro.m
	${OCTAVE_CMD} > $@

include ../../Makefile.test
