include ../../Makefile.test.globals

TESTS=	\
				t_VerificaSeZero_1

t_VerificaSeZero_1.out: t_VerificaSeZero_1.m \
												A \
												../VerificaSeZero.m
	${OCTAVE_CMD} > $@

include ../../Makefile.test
